import React from 'react';
const newsposts = [
    { id : 1, title:"When is the End ?", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
    { id : 2, title:"now we know", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
    { id : 3, title:"Truths about Buhari's Administration ?", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
    { id : 4, title:"Jesus the savior of the World?", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
    { id : 5, title:"Gbajaiamila knows the truth", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
    { id : 6, title:"Then where can we go ?", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
    { id : 7, title:"The ultimate survival", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
    { id : 8, title:"Three things to do before marriage", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
    { id : 9, title:"Why are there no Streeters ?", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
    { id : 10, title:"Nigeria @ 50. The Truth !", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
    { id : 11, title:"Nigeria is the place", body:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi nam facilis soluta. Quos consequatur aut, similique dolorem harum iste. Culpa neque quam eius id illo sunt, tempora dolorem! Illo, harum?Praesentium nobis enim quas aperiam laboriosam unde dolores, dicta similique repudiandae, a non tempora illo at mollitia? Ea autem natus exercitationem mollitia laboriosam quos tempore? Natus dignissimos totam error! Quos!Ducimus, officia impedit. Laborum asperiores amet sapiente officiis quam nam molestiae tempore quidem! Soluta est repellendus hic labore accusamus quibusdam officiis harum modi placeat vitae! Quasi ut dolorum adipisci vel." },
]

export default newsposts;